// Real Job Data - Updated January 2026
// This file is auto-generated by scraper.py

const jobsData = [
    {
        "title": "Police Jobs 2026: Latest Constable, SI, Inspector Jobs \u2013 43001 Vacancies",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2014/06/police-jobs-vacancy.html",
        "id": 49
    },
    {
        "title": "272 Scientist & Research Govt Jobs 2026",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2022/07/Scientist-Jobs.html",
        "id": 47
    },
    {
        "title": "Latest MCA Govt Jobs 2026 (513 Vacancies Opening)",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2014/08/MCA-Jobs.html",
        "id": 45
    },
    {
        "title": "NABARD Development Assistant Recruitment 2026 (162 Vacancies) | Notification Pdf, Online Form",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/nabard-development-assistant.html",
        "id": 43
    },
    {
        "title": "Indbank Recruitment 2026 - Apply for 20 Relationship Manager, Dealer & Other Posts",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/indbank-recruitment.html",
        "id": 41
    },
    {
        "title": "Central Bank of India Officer Recruitment 2026 (350 Vacancies) Online Form & Notification",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/central-bank-of-india-officer.html",
        "id": 39
    },
    {
        "title": "NCERT Recruitment 2026 Apply Online for 173 Non Academic Vacancies | Last Date 30.01.2026",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2025/12/ncert-recruitment-2026.html",
        "id": 37
    },
    {
        "title": "Exim Bank Management Trainee Recruitment 2026 Online Form (40 Vacancies)",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/exim-bank-management-trainee.html",
        "id": 35
    },
    {
        "title": "Latest MBA Govt Jobs 2026 (836 Vacancies Open Now)",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2014/08/MBA-Govt-Jobs.html",
        "id": 33
    },
    {
        "title": "IISER Tirupati Non Teaching Recruitment 2026 - Apply Online for 22 Vacancies",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/iiser-tirupati-non-teaching-recruitment.html",
        "id": 31
    },
    {
        "title": "42294 Assistant Govt Job Vacancies 2026",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2019/08/Assistant-Govt-Jobs.html",
        "id": 29
    },
    {
        "title": "IIITDM Kurnool Non Teaching Recruitment 2026 Apply Online for 18 Vacancies | Last Date 24.01.2026",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/iiitdm-kurnool-non-teaching-recruitment.html",
        "id": 27
    },
    {
        "title": "Employment News 24 to 30 January 2026: PDF Download & Weekly Notifications",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2017/04/Employment-News.html",
        "id": 25
    },
    {
        "title": "NIELIT Staff Car Driver Recruitment 2026 Apply Online (04 Posts)",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/nielit-staff-car-driver-recruitment.html",
        "id": 23
    },
    {
        "title": "CSIR CCMB Recruitment 2026 - Apply Online for 80 Technician, Assistant & Officer Posts",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/csir-ccmb-recruitment-2026-apply-online.html",
        "id": 21
    },
    {
        "title": "NHAI Deputy Manager Technical Recruitment 2026 \u2013 Apply Online for 40 Vacancies",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/nhai-deputy-manager-technical.html",
        "id": 19
    },
    {
        "title": "Indian Navy SSC Officer Recruitment 2026 Notification & Online Form (260 Posts)",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2016/04/Indian-Navy-SSC-Officer-Recruitment.html",
        "id": 17
    },
    {
        "title": "4422 Bank Jobs Openings 2026 \u2013 Latest Banking Job Notifications",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2013/08/bank-jobs-openings-august-2013.html",
        "id": 15
    },
    {
        "title": "Indian Railway Jobs 2026 \u2013 22406 Vacancies Open Now",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2013/09/railway-jobs-recruitment.html",
        "id": 13
    },
    {
        "title": "CSIR IITR MTS & Driver Recruitment 2026 Apply Online (06 Vacancies)",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/csir-iitr-mts-driver-recruitment-2026.html",
        "id": 11
    },
    {
        "title": "IMA Dehradun Faculty Recruitment 2026 Apply for 10 Vacancies",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/ima-dehradun-faculty-recruitment-2026.html",
        "id": 9
    },
    {
        "title": "Govt of India Press Apprenticeship Recruitment 2026 Apply Online (26 Vacancies)",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/govt-of-india-press-apprenticeship.html",
        "id": 7
    },
    {
        "title": "HVF Avadi Junior Technician Recruitment 2026 Apply for 220 Posts",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2025/06/hvf-avadi-junior-technician-recruitment.html",
        "id": 5
    },
    {
        "title": "Central University of Kerala Faculty Recruitment 2026 Apply Online (12 Vacancies)",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2026/01/central-university-of-kerala-faculty_24.html",
        "id": 3
    },
    {
        "title": "Government Jobs 2026 (137864 Latest Govt Jobs Opening)",
        "type": "govt",
        "location": "All India",
        "qualification": "See Notification",
        "lastDate": "Check Link",
        "urgent": false,
        "vacancies": "Check Link",
        "applyLink": "https://www.indgovtjobs.in/2015/10/Government-Jobs.html",
        "id": 1
    }
];

const examsData = [];

const resultsData = [];

const admitCardsData = [];

const allJobsData = [...jobsData];
